### ISSUE TITLE
Questions for Autorate.sh

### ISSUE THREAD

**Issue by richb-hanover** [lynxthecat/sqm-autorate#7]
As I was proofreading the README.md, I came up with some questions:

1. I don't understand why someone would limit the max setting of the autorate.sh below the link's maximum. If the ISP can provide 10 to 30 mbps, what is the motivation to artificially set the max setting to 25mbps?

2. What if my minimum setting is grossly incorrect? What if I set the min to 4mbps, but my carrier really can only provide 3mbps from time to time?
	- Do I get bad latency during those periods?
	- How could I ever know (besides noticing bad latency)?

3. And similarly, what if the max setting is too low? What if conditions improve, and my carrier can provide 20% or 50% higher speeds from time to time? (I think that's just lost bandwidth. And could I ever know?)

4. Does autorate.sh keep any long-term stats that might help inform these questions? Does it record "minimum minimum" and "maximum maximum"? (I'm not sure what these would look like, or even how useful they might be...)

5. All these questions lead up to my final one: Why not let autorate.sh determine the rates entirely on its own? Why provide these "hints" for min and max that might turn out to be wrong? What would be the bad effect of setting min to 0 and max to MAXINT and letting autorate.sh "figure it out"? As I understand autorate.sh today, it seems to me:

   - If I set the min too high, there'll be added latency, even though autorate.sh should be able to accommodate the lower speed
   - If I set the max too low, it's the same thing: autorate.sh *could* adjust, but my setting prevents it.

I confess that I have not read every word on the Forum thread, so I don't know if it has been discussed there. I am prepared to believe that people have observed bad latencies when the link speeds skirt the edges (low or high), and it's necessary to put up guard rails to keep latency in bounds.

Thanks.

**Comment by lynxthecat** [comment]
Concerning 1) 

The principle of operation of the script is that it increases bandwidth, then checks RTT, and so long as there is no RTT spike, keeps raising the bandwidth. So up until the maximum has been hit, the script will keep pushing higher until it encounters an RTT spike. This inevitably results in letting through some bufferbloat. 

Predictive bandwidth approaches try to resolve this by measuring packet spacing and the like, but nobody has been able to show that this actually works (albeit the MIT sprout algorithm - http://alfalfa.mit.edu/ - claims to have achieved this - and at least @Lochnair on the OpenWrt forum has indicated he is trying this out). 

By setting a maximum below the best a line can achieve, the script will just leave it there. So whilst the true capacity is beyond that, and the load is maintained, the script will just hold the bandwidth there. Perhaps the user is fine with just 30Mbit/s on a variable rate line that gives bursts up to 80Mbit/s. 

Concerning 2)

Yes in this case the script will keep the bandwidth too high and significant bufferbloat will be allowed through whilst there is enough load to saturate the connection. I think it would be possible to monitor RTT under no load and then compare with RTT under load and use that to alert the user that the minimum appears set too low. But a big principle so far has been to keep everything simple. Lots of individuals come up with various hacks and modifications, but most only work for some use cases or introduce a lot of complexity. 

Concerning 3) 

Yes I think just lost bandwidth, albeit with the benefit of not testing the ceiling and so letting through bufferbloat as described above in 1). 

Concerning 4)

Not really. Just every second the encountered RTT, the present baseline RTT, download and upload rates set, time, etc. 

Concerning 5) 

I think a problem is that under no load the script does not know what the capacity is. At the moment it therefore decays down the minimum 'safe' bandwidth as set by the user. 

This script is passive as it does not inject any packets (aside from the RTT checks). Other approaches disable SQM and saturate the connection and use that to measure capacity bandwidth. But this involves huge interruption to the connection in order to ascertain the bandwidth. 

@moeller0 can likely better answer some of these questions than I can.

**Comment by moeller0** [comment]
ad 1) many ISPs put in a shaper to limit users to not more than their contracted maximum access speed, but unfortunately these shapers are not necessarily configured as well as one would like, so putting in a hard upper boundary seems fine as it will avoid repeated epochs of bloat spikes. If a user feels lucky that limit can simply be set higher than the contracted speed. Also I think we scale stuff by (max - min) so if we jettison max we would need another toggle.

ad 2) yes, the minimum is as low as the script will allow the rates to drop, if that is wrong users will need to adjust it. Setting this to zero (basically no lower limit) is not going to be useful.... as then the transmission times of individual will simply get unacceptably high (which at the very least requires an adaptive delay threshold increasing complexity).

That said, we are pondering introducing a default rate the script will converge too lacking additional data, which would allow to define a lower minimum, but minimum zero will still not work, so this really does not solve the issue that the user needs to configure some numbers properly for the script to work.

ad 3) Yes too low a maximum will leave potential throughput on the table.

That said having a min and a max will make sure that any errors of the script are bounded so a link should (assuming halfway competent selection of these numbers) stay usable.

ad 5) ATM both min and max act as safety valves should the script's logic do silly things (like not having considered important corner-cases). And they also serve to allow to use a linear increase/decrease scale, otherwise the rate adjustment stepsize needs to be selected by other means. Here one could emulate what TCP does, but then the inner TCPs will sort of see a "squared" effect of their own adjustments since these will now interact with the shapers adjustments.
In all honesty, I am amazed how well this works at 1 second tick rate, I had naively assumed such an approach would require stable shaper rates for epochs in the 10 seconds range.... I guess that depends a bit on a) the typical RTTs of TCP connections and b) whether the speed changes introduced by this script are noticeably worse than those encpountered without the script.

**Comment by lynxthecat** [comment]
BTW @richb-hanover my overall goal when I wrote the first post on the OpenWrt thread was to see if I could encourage the CAKE developers to replace 'autorate-ingress' with something that actually works. In this connection I poked fun about the CAKE being only half-baked, because as a form of congestion control it only works on fixed rate connections, and so feels incomplete. I personally think a long term goal should be to get something more robust than what this script achieves at the moment. And if it were to be implemented in C it could be made to run faster. I think an issue though is finding out what routine or approach works best. So perhaps the experimentation at the moment is still important before any robust solution is codified.

**Comment by richb-hanover** [comment]
Thanks for these answers. 

I am just pushing my luck here... We traditionally promote SQM as "No Knobs Required". That's not quite true - you need to set CAKE/fq_codel up & down rates. And maybe adjust the per-packet overhead, and some other twiddles. That said, I am hoping to make it so that CAKE + autorate.sh truly is "no knobs".

Specifically, it would be slick if we could completely eliminate the requirement to specify the min and max values, for the following reasons:

1. People may not really know the limits, so they're just guessing when they set them initially
2. ISPs may change the link speeds (down, or up) and people won't know to adjust their router
3. We no longer have to document how to set `min_dl_rate` etc. in the README (which people won't read, anyway :-))

I realize that the script is passive - it just adjusts CAKE's parameters based on the recent behavior. It also (currently) has no memory (so it would be bad to adjust downward to zero...) Perhaps I'm suggesting that there could be a way to keep long-term `min-seen` and `max-seen` variables in lieu of the `min_dl_rate` etc. settings.

I would welcome @moeller0  to weigh in.

Also: if you think it would be helpful/preferable, I'm happy to bring these questions to the Forum. 

And to respond to your most recent comment... Your approach is exactly correct. Building a prototype that is easy to modify and works well enough to criticize is a perfect first step. Once we understand the corner cases (in a bash script; in a lua script; using sprout, etc) we can decide how to "productize" it into a single package. Thanks again.

**Comment by lynxthecat** [comment]
Totally agree. BTW @richb-hanover one way of thinking about the script is like a turbo function above the ordinary CAKE bandwidth. On ultra high load it can ramp up the bandwidth until it overheats or in our case encounters RTT spikes.  At least the maximum rate could be dispensed with. The harder thing is the minimum. Also it has been proposed on the thread to set even a third extra rate between min and max so that it decays towards  this intermediate rate rather than the minimum. But this is yet more complexity. 

@moeller0 thoughts on this?

**Comment by moeller0** [comment]
"That said, I am hoping to make it so that CAKE + autorate.sh truly is "no knobs"."

No can do, we still have the per-packet-overhead issue ;)

"People may not really know the limits, so they're just guessing when they set them initially"

True, but often people know the maximum (as that typically is the number that is advertised). 

"ISPs may change the link speeds (down, or up) and people won't know to adjust their router"

Yes, true and inconvenient, I wish ISPs would simply deploy competent AQMs on their links so we wpuld not need to second guess them.

"We no longer have to document how to set min_dl_rate etc. in the README (which people won't read, anyway :-))"

;)

"The minimum could be set by measuring RTT on no load and verifying that RTT during saturation at the present minimum bandwidth is not increased. If it is increased, the minimum needs to be reduced further. Make sense?"

In theory yes, in practice we run into the problem that there is lots of potential for the RTT to increase independent of the load on the access link (that we are trying to control here) so we need to somehow make sure that bad peering of our ISP to our reflectors does not result in the script automatically driving the min to zero. So we want some learning (when it helps) but we want also to be resilient against those RTT changes that we can not control from our vantage point, but all we see is the aggregate RTT. I am sure others can come up with better algorithms here that do more of the right thing, but for me having the hard lower and upper limit leaves a nice fuzzy feeling in my innards knowing that the heuristic is only going to play in that range we allow it to.

**Comment by lynxthecat** [comment]
Regarding the overhead I have the feeling that the vast majority of OpenWrt users (myself included) have no idea how to set that. So setting that is a bit random. Like in my case I think I set it to 92 based on WireGuard overhead and speculation about LTE overhead. I see the point about hard limits being reassuring, yet I also have the experience myself of being a bit clueless about the overhead aspect. 

There is something highly attractive about SQM activated/deactivated and it just working for the majority of cases. CAKE is pretty close to that, and with with a little more baking could surely achieve that or something very close. 

Might the other CAKE developers be interested in helping out with this autorate problem and potentially arriving at a fully automatic setup? I am really just a humble CAKE padawan facing the limits of my skills and knowledge. With a few more jedi masters I have the feeling some more significant progress could be made that would benefit many.

If anything this script and thread had demonstrated massive interest in the issue. So the demand is there!

**Comment by lynxthecat** [comment]
@richb-hanover I have implemented a version of the script in the 'experimental' branch that takes only a single set rate and then adjusts the download and upload rates accordingly. On my LTE connection it seems to be working.

**Comment by richb-hanover** [comment]
Quick question: I fear that I have forked the discussion. Should I ask the next question below on the Forum? Or is it best to keep it here?

**Comment by richb-hanover** [comment]
> @richb-hanover I have implemented a version of the script in the 'experimental' branch that takes only a single set rate and then adjusts the download and upload rates accordingly. On my LTE connection it seems to be working.

I've been offline for a couple days, and a lot has been happening here and on the Forum topic. I'm feeling behind the eight ball, so could you give me a quick overview of the experimental branch's operation?

- It sounds as if the experimental branch has one "setpoint" rate for each direction. (That would actually be terrific. The user could enter a value for each direction, as they do now. Or maybe `autorate.sh` could re-set that setpoint by running a speed test each time it brings up the interface or some other trigger...)

- `autorate.sh` then manages the traffic as it in the past, but in the absence of traffic, its speed setting drifts toward that setpoint.

Is this close to right? Thanks.

**Comment by lynxthecat** [comment]
I think here is fine too as the forum thread has a lot of clutter not necessarily associated with the overall functionality of the routine. 

Concerning your question: I think so. Now user just sets ONE rate in each direction - the steady state base rate. 

**On high load**, the script increases the rate in the heavily loaded direction (download, upload or both) so long as no RTT spike is detected. If an RTT spike is detected, it will decrease the rate in download and/or upload in dependence on whether there is a high load in each direction during the tick that generated the RTT spike. 

**On low load**, the script decays the rate towards the base rate (either up or down). 

@moeller0 points out that my high load logic has the problem that we may not decrease the offending bandwidth on an RTT spike. So for example it could be that Rx is 80% loaded and Tx is 40% loaded, but it is the Tx that is causing the bufferbloat (even at the 40%), but we only decrease the Rx rate to try to deal with bufferbloat, and we keep on decreasing with no effect. This concern is entirely legitimate and may explain my own experience of the script killing bandwidth down to zero on download. 

The reason for my kludge of reducing rate only in direction that is heavily loaded is that otherwise we decrease both rates heavily even on single loading direction. But I think we should go back to this suboptimal behaviour given @moeller0's observation above. 

A significant improvement would be to get pings based on timestamps and use that to ascertain which direction is causing the RTT spike. There has been some discussion on that in the forum, and when I get more time I am going to try to implement something along these lines, but it raises a lot of new problems in terms of how to deal with the pings, timestamps, deltas, etc. It is not clear in my mind how to do this. Although @moeller0 has given me some pointers.

The main logic in the experimental branch is presently as follows. Please let me know if you see any issues:

`        # in case of supra-threshold RTT spikes decrease the rate so long as there is a load
        if awk "BEGIN {exit !(($cur_delta_RTT >= $cur_max_delta_RTT) && $cur_load >= $cur_load_thresh)}"; then
            next_rate=$( call_awk "int( ${cur_rate}*(1-${cur_rate_adjust_RTT_spike}) )" )
        else
            # ... otherwise determine whether to increase or decrease the rate in dependence on load
            # high load, so we would like to increase the rate
            if awk "BEGIN {exit !($cur_load >= $cur_load_thresh)}"; then
                next_rate=$( call_awk "int( ${cur_rate}*(1+${cur_rate_adjust_load_high}) )" )
            else
                # low load, so determine whether to decay down towards base rate, decay up towards base rate, or set as base rate
                cur_rate_decayed_down=$( call_awk "int( ${cur_rate}*(1-${cur_rate_adjust_load_low}) )" )
                cur_rate_decayed_up=$( call_awk "int( ${cur_rate}*(1+${cur_rate_adjust_load_low}) )" )

                # gently decrease to steady state rate
                if awk "BEGIN {exit !($cur_rate_decayed_down > $cur_base_rate)}"; then
                        next_rate=$cur_rate_decayed_down
                # gently increase to steady state rate
                elif awk "BEGIN {exit !($cur_rate_decayed_up < $cur_base_rate)}"; then
                        next_rate=$cur_rate_decayed_up
                # steady state has been reached
                else
                        next_rate=$cur_base_rate
        fi
        fi
        fi`


The line:

`if awk "BEGIN {exit !(($cur_delta_RTT >= $cur_max_delta_RTT) && $cur_load >= $cur_load_thresh)}"; then`

Should probably go back to:

`if awk "BEGIN {exit !(($cur_delta_RTT >= $cur_max_delta_RTT))}"; then`

So that we just decrease BOTH rates on RTT spike. This is really annoying, but I think @moeller0 is right about my gamble to only reduce the loaded direction rate being too big a gamble.

**Comment by moeller0** [comment]
+1; it would be great to get a reliable estimate which rate to lower. But in the above code, why not re-add the old hard minimum and maximum clamping sections again guarded with a test whether the variable is empty like:
```
if [ -z "$STRING" ]; then
    # $STRING is empty
fi


if [ "$cur_min_rate" -gt "-1" ]; then
	# make sure to only return rates between cur_min_rate and cur_max_rate
        if awk "BEGIN {exit !($next_rate < $cur_min_rate)}"; then
            next_rate=$cur_min_rate;
        fi
fi

if [ "$cur_max_rate" -gt "-1" ]; then
        if awk "BEGIN {exit !($next_rate > $cur_max_rate)}"; then
            next_rate=$cur_max_rate;
        fi
fi
```

The idea would be to use -1 as marker to tell the script to ignore that parameter. Mind you I did not test this at all so this might not work at all....

**Comment by richb-hanover** [comment]
A few comments:

- This is good news. I am hopeful that this "one setpoint" procedure can work. It's simpler to explain, and gives people (like me) fewer places to "do it wrong".
- Furthermore, I can then envision an initialization trigger that tests the attainable speeds _right now,_ and that the autorate algorithm can adopt those as the settings. 
- This would be "almost no knobs" (Yes, @moeller0, I remember that ATM framing is still a hassle, and definitely needs to be accounted for.)
- Finally, I am aching to try this here. I have a LTE modem feeding a router. But it's about an hour's drive away. (And family members rely on it when I'm not there...) So I need to get Wireguard installed so I can administer it remotely, then let it burn in for a bit before I screw up my courage to deploy it. Hopefully, before the Christmas holiday.
- Thanks again!

**Comment by moeller0** [comment]
> * This would be "almost no knobs" (Yes, @moeller0, I remember that ATM framing is still a hassle, and definitely needs to be accounted for.)

Well, actually, as much as it pains me (*), this autorate approach should allow to get away with incorrect overhead settings, as it directly assess the result of either rate or overhead being incorrect (and for a given packet size mix, a wrong overhead setting can be remedied with an equally an opposing wrong shaper setting). Sure it will be not as smooth as setting this correctly but overall it should do the right thing, same with ATM cell quantization overhead, given that typically high load results in most packets being of the same fixed size.... 

(*) No real pain involved, but I guess that getting the overhead setting correctly will help making the control loop a bit tighter as it will remove one packet-size dependent source of variance/error.

> * Furthermore, I can then envision an initialization trigger that tests the attainable speeds _right now,_ and that the autorate algorithm can adopt those as the settings.

That would require a router beefy enough to actually saturate the access link reliably... probably true for the raspberry pi as router or better crowd, not sure though how that would be at the bargain end of the router range. That said, recommending to disable the script and run a few speedtests and then set the default rate to 90% of that rate should be doable, no?

**Comment by dlakelan** [comment]
Or set the script into "eval mode" and trigger a speed test from the LAN, have it watch what happens and then store that to a config file.
